// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package ksyun

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatKmiFilterOptions is an auto-generated flat version of KmiFilterOptions.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatKmiFilterOptions struct {
	MostRecent  *bool   `mapstructure:"most_recent" cty:"most_recent" hcl:"most_recent"`
	ImageSource *string `mapstructure:"image_source" cty:"image_source" hcl:"image_source"`
	NameRegex   *string `mapstructure:"name_regex" cty:"name_regex" hcl:"name_regex"`
	Platform    *string `mapstructure:"platform" cty:"platform" hcl:"platform"`
}

// FlatMapstructure returns a new FlatKmiFilterOptions.
// FlatKmiFilterOptions is an auto-generated flat version of KmiFilterOptions.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*KmiFilterOptions) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatKmiFilterOptions)
}

// HCL2Spec returns the hcl spec of a KmiFilterOptions.
// This spec is used by HCL to read the fields of KmiFilterOptions.
// The decoded values from this spec will then be applied to a FlatKmiFilterOptions.
func (*FlatKmiFilterOptions) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"most_recent":  &hcldec.AttrSpec{Name: "most_recent", Type: cty.Bool, Required: false},
		"image_source": &hcldec.AttrSpec{Name: "image_source", Type: cty.String, Required: false},
		"name_regex":   &hcldec.AttrSpec{Name: "name_regex", Type: cty.String, Required: false},
		"platform":     &hcldec.AttrSpec{Name: "platform", Type: cty.String, Required: false},
	}
	return s
}
